- alias: 'Dishwasher done notification'
  trigger:
    platform: state
    entity_id: sensor.dishwasher
    from: 'active'
    to: 'finished'
  action:
    service: notify.home_bot
    data:
      title: dishwasher done picture
      message: Dishwasher done!
      data:
        photo:
          - file: /config/images/dishwasher_finished.png
            caption: Dishwasher is finished!

- alias: 'Dishwasher done notification Maria'
  trigger:
    platform: state
    entity_id: sensor.dishwasher
    from: 'active'
    to: 'finished'
  action:
    service: notify.telegram_maria
    data:
      title: dishwasher done picture
      message: Dishwasher done!
      data:
        photo:
          - file: /config/images/dishwasher_finished.png
            caption: Dishwasher is finished!

- alias: 'Dishwasher done notification Costas'
  trigger:
    platform: state
    entity_id: sensor.dishwasher
    from: 'active'
    to: 'finished'
  action:
    service: notify.telegram_costas
    data:
      title: dishwasher done picture
      message: Dishwasher done!
      data:
        photo:
          - file: /config/images/dishwasher_finished.png
            caption: Dishwasher is finished!