- platform: speedtest
  server_id: 6247
  minute:
    - 0
    - 15
    - 30
    - 45
  monitored_conditions:
    - ping
    - download
    - upload

- platform: fastdotcom
  minute:
    - 2
    - 17
    - 32
    - 47