- platform: mqtt
  state_topic: 'home/study/inner_left'
  name: 'study_inner_left_temperature'
  friendly_name: 'Study inner left temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/study/inner_left'
  name: 'study_inner_left_humidity'
  friendly_name: 'Study inner left humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/study/inner_right'
  name: 'study_inner_right_temperature'
  friendly_name: 'Study inner right temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/study/inner_right'
  name: 'study_inner_right_humidity'
  friendly_name: 'Study inner right humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/study/outer_right'
  name: 'study_outer_right_temperature'
  friendly_name: 'Study outer right temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/study/outer_right'
  name: 'study_outer_right_humidity'
  friendly_name: 'Study outer right humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/study/outer_left'
  name: 'study_outer_left_temperature'
  friendly_name: 'Study outer left temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/study/outer_left'
  name: 'study_outer_left_humidity'
  friendly_name: 'Study outer left humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: template
  sensors:
    study_average_temperature:
      friendly_name: 'Study Temperature'
      unit_of_measurement: 'C'
      value_template: >-
        {{ ((float(states.sensor.study_inner_left_temperature.state) +
             float(states.sensor.study_inner_right_temperature.state) +
             float(states.sensor.study_outer_right_temperature.state) +
             float(states.sensor.study_outer_left_temperature.state)) / 4) | round(2) }}

- platform: template
  sensors:
    study_average_humidity:
      friendly_name: 'Study Humidity'
      unit_of_measurement: '%'
      value_template: >-
        {{ ((float(states.sensor.study_inner_left_humidity.state) +
             float(states.sensor.study_inner_right_humidity.state) +
             float(states.sensor.study_outer_right_humidity.state) +
             float(states.sensor.study_outer_left_humidity.state)) / 4) | round(2) }}