- platform: mqtt
  state_topic: 'home/bedroom/outer_right_corner'
  name: 'bedroom_outer_right_temperature'
  friendly_name: 'Bedroom outer right temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/bedroom/outer_right_corner'
  name: 'bedroom_outer_right_humidity'
  friendly_name: 'Bedroom outer right humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/bedroom/outer_left_corner'
  name: 'bedroom_outer_left_temperature'
  friendly_name: 'Bedroom outer left temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/bedroom/outer_left_corner'
  name: 'bedroom_outer_left_humidity'
  friendly_name: 'Bedroom outer left humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/bedroom/inner_middle'
  name: 'bedroom_inner_middle_temperature'
  friendly_name: 'Bedroom inner middle temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/bedroom/inner_middle'
  name: 'bedroom_inner_middle_humidity'
  friendly_name: 'Bedroom inner middle humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: template
  sensors:
    bedroom_average_temperature:
      friendly_name: 'Bedroom Temperature'
      unit_of_measurement: 'C'
      value_template: >-
        {{ ((float(states.sensor.bedroom_outer_right_temperature.state) +
             float(states.sensor.bedroom_outer_left_temperature.state) +
             float(states.sensor.bedroom_inner_middle_temperature.state)) / 3) | round(2) }}

- platform: template
  sensors:
    bedroom_average_humidity:
      friendly_name: 'Bedroom Humidity'
      unit_of_measurement: '%'
      value_template: >-
        {{ ((float(states.sensor.bedroom_outer_right_humidity.state) +
             float(states.sensor.bedroom_outer_left_humidity.state) +
             float(states.sensor.bedroom_inner_middle_humidity.state)) / 3) | round(2) }}