- alias: 'Washing Machine done notification'
  trigger:
    platform: state
    entity_id: sensor.washing_machine
    from: 'active'
    to: 'finished'
  action:
    service: notify.home_bot
    data:
      title: Washing Machine done picture
      message: Washing Machine done!
      data:
        photo:
          - file: /config/images/washing_machine_finished.png
            caption: Washing Machine is finished!

- alias: 'Dryer done notification'
  trigger:
    platform: state
    entity_id: sensor.dryer
    from: 'active'
    to: 'finished'
  action:
    service: notify.home_bot
    data:
      title: Dryer done picture
      message: Dryer done!
      data:
        photo:
          - file: /config/images/dryer_finished.png
            caption: Dryer is finished!

- alias: 'Dishwasher done notification 2'
  trigger:
    platform: state
    entity_id: sensor.dishwasher
    from: 'active'
    to: 'off'
  action:
    service: notify.home_bot
    data:
      title: dishwasher done picture
      message: Dishwasher done!
      data:
        photo:
          - file: /config/images/dishwasher_finished.png
            caption: Dishwasher is finished (alternate)!

- alias: 'Dishwasher done notification'
  trigger:
    platform: state
    entity_id: sensor.dishwasher
    from: 'active'
    to: 'finished'
  action:
    service: notify.home_bot
    data:
      title: dishwasher done picture
      message: Dishwasher done!
      data:
        photo:
          - file: /config/images/dishwasher_finished.png
            caption: Dishwasher is finished!


- alias: 'Porch light ON on sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    service: light.turn_on
    entity_id: light.entrance_front_door
    data:
      transition: 1800
      brightness: 64

- alias: 'Porch light OFF on sunrise'
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:15:00"
  action:
    service: light.turn_off
    entity_id: light.entrance_front_door
    data:
      transition: 1800
