homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longtitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  whitelist_external_dirs: /config/images

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

toon:
  username: !secret toon_username
  password: !secret toon_password

group: !include groups.yaml

light: !include hue_lights.yaml

sensor: !include_dir_merge_list sensors/

telegram_bot: !include telegram_bot.yaml

notify: !include notifications.yaml

media_player: !include media_players.yaml

device_tracker: !include ping_tracking.yaml

mqtt: !include mqtt.yaml

influxdb: !include influxdb.yaml

automation: !include_dir_merge_list automations/

switch: !include switches.yaml

weblink: !include weblinks.yaml
