homeassistant:
  name: Home
  latitude: 52.332913
  longitude: 4.9418919
  elevation: 1.5
  unit_system: metric
  time_zone: Europe/Amsterdam
  whitelist_external_dirs: /config/images

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

toon:
  username: costas.tyf@gmail.com
  password: !secret toon_password

group: !include groups.yaml

light: !include hue_lights.yaml

sensor: !include sensors.yaml

telegram_bot: !include telegram_bot.yaml

notify: !include notifications.yaml

media_player: !include media_players.yaml

device_tracker: !include ping_tracking.yaml

mqtt: !include mqtt.yaml

influxdb: !include influxdb.yaml

automation: !include automations.yaml

switch: !include switches.yaml

weblink: !include weblinks.yaml
