default_view:
  view: yes
  entities:
    - sun.sun
    - climate.toon_van_eneco
    - sensor.yr_temperature
    - sensor.yr_humidity
    - sensor.yr_cloudiness
    - sensor.home_average_temperature
    - sensor.home_average_humidity
    - sensor.smokedetector_smoke_detector
    - zone.home
    - zone.work
    - weblink.home_graphs

bedroom:
  name: Bedroom
  view: true
  entities:
    - light.bedroom
    - light.bedroom_ceiling
    - switch.costass_blanket
    - switch.marias_blanket
    - switch.bedroom_panel_switch
    - weblink.bedroom_graphs

living_room:
  name: Living Room
  view: true
  entities:
    - device_tracker.philips_remote
    - light.living_room
    - light.living_room_hanging_light
    - light.living_room_standing_lamp
    - light.tv_bias_light
    - media_player.kodi
    - weblink.living_room_graphs
    # - media_player.philips_ott_2000_remote
    # - media_player.samsung_tv_remote

kitchen:
  name: Kitchen
  view: true
  entities:
    - sensor.dishwasher
    - automation.dishwasher_done_notification
    - automation.dishwasher_done_notification_maria
    - automation.dishwasher_done_notification_costas
    - light.kitchen
    - light.kitchen_ceiling
    - light.kitchen_shelves
    - light.soul_light
    - switch.dishwasher
    - weblink.kitchen_graphs

entrance:
  name: Entrance
  view: true
  entities:
    - automation.entrance_light_off_on_sunrise
    - automation.entrance_light_on_on_sunset
    - light.entrance
    - light.entrance_front_door

study:
  name: Study
  view: true
  entities:
    - device_tracker.printer
    - light.study
    - light.study_ceiling_left
    - light.study_ceiling_right
    - weblink.study_graphs

washing_room:
  name: Washing Room
  view: true
  entities:
    - automation.dryer_done_notification
    - automation.dryer_done_notification_maria
    - automation.dryer_done_notification_costas
    - automation.washing_machine_done_notification
    - automation.washing_machine_done_notification_maria
    - automation.washing_machine_done_notification_costas
    - sensor.dryer
    - sensor.washing_machine
    - switch.dryer
    - switch.washer
    - weblink.washing_room_graphs

guest_room:
  name: Guest Room
  view: false
  entities:

bathroom:
  name: Bathroom
  view: false
  entities:

back_porch:
  name: Back Porch
  view: false
  entities:
#    - switch.porch_hanging_lights

back_garden:
  name: Back Garden
  view: false
  entities:

front_garden:
  name: Front Garden
  view: false
  entities:

front_porch:
  name: Front Porch
  view: false
  entities:
