philips_remote:
  hide_if_away: false
  mac:
  name: philips remote
  picture:
  track: true
  vendor:

printer:
  hide_if_away: false
  mac:
  name: printer
  picture:
  track: true
  vendor:

costas_blanket:
  hide_if_away: false
  mac:
  name: costas blanket
  picture:
  track: true
  vendor:

marias_blanket:
  hide_if_away: false
  mac:
  name: marias blanket
  picture:
  track: true
  vendor:
