home_latitude:
home_longtitude:
home_elevation:
home_timezone:

toon_username:
toon_password:

hue_base_ip:

influxdb_host_ip:
influxdb_username:
influxdb_admin_password:
influxdb_database:

kodi_host_ip:
kodi_username:
kodi_password:

telegram_api_key:
telegram_group_id:
telegram_costas_id:
telegram_maria_id:

pushbullet_api_key:

philips_ott_2000_host_ip:

cast_ip:

samsung_tv_ip:

mqtt_host_ip:

costas_phone_ip:
maria_phone_ip:
printer_ip:
philips_remote_ip:

costas_blanket_api:
costas_blanket_ip:
marias_blanket_api:
marias_blanket_ip:
#porch_hanging_lights_api:
#porch_hanging_lights_ip:


home_dashboard_url:

bedroom_dashboard_url:

study_dashboard_url:

washing_room_dashboard_url:

kitchen_dashboard_url:

living_room_dashboard_url:

zwave_network_key: