
- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - humidity
    - cloudiness
    - dewpointTemperature

- platform: speedtest
  server_id: 6247
  minute:
    - 0
    - 15
    - 30
    - 45
  monitored_conditions:
    - ping
    - download
    - upload

- platform: fastdotcom
  minute:
    - 2
    - 17
    - 32
    - 47

- platform: template
  sensors:
    dryer:
      friendly_name: 'Dryer'
      entity_id: sensor.dryer_current_power
      value_template: >-
          {% set power_usage = (states.sensor.dryer_current_power.state | float) %}
          {%- if power_usage < 1.0 %}
              off
          {%  elif power_usage >= 2.6 %}
              active
          {% elif 1.1 <= power_usage <= 2.5 %}
              {%- if states.sensor.dryer.state == 'off' %}
                  on
              {%  elif states.sensor.dryer.state == 'active'  %}
                  finished
              {%- endif %}
          {%- endif %}

- platform: template
  sensors:
    washing_machine:
      friendly_name: 'Washing Machine'
      entity_id: sensor.washer_current_power
      value_template: >-
          {% set power_usage = (states.sensor.washer_current_power.state | float) %}
          {%- if power_usage <= 1.0 %}
              off
          {%  elif power_usage >= 2.0 %}
              active
          {% elif 1.1 <= power_usage <= 1.9 %}
              {%- if states.sensor.washing_machine.state == 'off' %}
                  on
              {%  elif states.sensor.washing_machine.state == 'active'  %}
                  finished
              {%- endif %}
          {%- endif %}

- platform: template
  sensors:
    dishwasher:
      friendly_name: 'Dishwasher'
      entity_id: sensor.dishwasher_current_power
      value_template: >-
          {% set power_usage = (states.sensor.dishwasher_current_power.state | float) %}
          {%- if power_usage == 0 %}
              off
          {%  elif power_usage >= 1.2 %}
              active
          {% elif power_usage <= 1.1 %}
              {%- if states.sensor.dishwasher.state == 'off' %}
                  on
              {%  elif states.sensor.dishwasher.state == 'active'  %}
                  finished
              {%- endif %}
          {%- endif %}

- platform: mqtt
  state_topic: 'home/bedroom/outer_right'
  name: 'bedroom_outer_right_temperature'
  friendly_name: 'Bedroom outer right temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/bedroom/outer_right'
  name: 'bedroom_outer_right_humidity'
  friendly_name: 'Bedroom outer right humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/bedroom/outer_left'
  name: 'bedroom_outer_left_temperature'
  friendly_name: 'Bedroom outer left temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/bedroom/outer_left'
  name: 'bedroom_outer_left_humidity'
  friendly_name: 'Bedroom outer left humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/bedroom/inner_middle'
  name: 'bedroom_inner_middle_temperature'
  friendly_name: 'Bedroom inner middle temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/bedroom/inner_middle'
  name: 'bedroom_inner_middle_humidity'
  friendly_name: 'Bedroom inner middle humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/study/inner_left'
  name: 'study_inner_left_temperature'
  friendly_name: 'Study inner left temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/study/inner_left'
  name: 'study_inner_left_humidity'
  friendly_name: 'Study inner left humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/study/inner_right'
  name: 'study_inner_right_temperature'
  friendly_name: 'Study inner right temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/study/inner_right'
  name: 'study_inner_right_humidity'
  friendly_name: 'Study inner right humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/study/outer_right'
  name: 'study_outer_right_temperature'
  friendly_name: 'Study outer right temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/study/outer_right'
  name: 'study_outer_right_humidity'
  friendly_name: 'Study outer right humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/study/outer_left'
  name: 'study_outer_left_temperature'
  friendly_name: 'Study outer left temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/study/outer_left'
  name: 'study_outer_left_humidity'
  friendly_name: 'Study outer left humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'home/washing_room/back'
  name: 'washing_room_back_temperature'
  friendly_name: 'Washing_Room back temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'home/washing_room/back'
  name: 'washing_room_back_humidity'
  friendly_name: 'Washing_Room back humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'
# 
# - platform: mqtt
#   state_topic: 'home/washing_room/front'
#   name: 'washing_room_front_temperature'
#   friendly_name: 'Washing_Room front temperature'
#   unit_of_measurement: 'C'
#   value_template: '{{ value_json.temperature }}'
#
# - platform: mqtt
#   state_topic: 'home/washing_room/front'
#   name: 'washing_room_front_humidity'
#   friendly_name: 'Washing_Room front humidity'
#   unit_of_measurement: '%'
#   value_template: '{{ value_json.humidity }}'
